#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 23, 2020 02:27:07 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global cantViajeros
    cantViajeros = tk.StringVar()
    global tch49
    tch49 = tk.StringVar()
    global clase
    clase = tk.StringVar()
    global distancia
    distancia = tk.StringVar()
    global precio
    precio = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def calcular():
    #datos ingresados
    cantidadViajeros=int(cantViajeros.get())
    distanciaViaje=int(distancia.get())
    precioViaje=float(precio.get())
    tipoViaje=tch49.get()
    claseSel=""


    print(tipoViaje)

    if clase.get()=="Turista":
        precioFinal=cantidadViajeros*distanciaViaje*precioViaje
    elif clase.get()=="Primera":
        precioFinal=(cantidadViajeros*distanciaViaje*precioViaje)*1.5
    else:
        precioFinal=(cantidadViajeros*distanciaViaje*precioViaje)*2

    print(precioFinal)
    if tipoViaje=="1":
        precioFinal=precioFinal*1.5

    w.lblTotalPagar.configure(text=
                              f"{precioFinal}")


def salir():
    destroy_window()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import trenIrala
    trenIrala.vp_start_gui()




