#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 23, 2020 02:27:03 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import trenIrala_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    trenIrala_support.set_Tk_var()
    top = titulo1 (root)
    trenIrala_support.init(root, top)
    root.mainloop()

w = None
def create_titulo1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_titulo1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    trenIrala_support.set_Tk_var()
    top = titulo1 (w)
    trenIrala_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_titulo1():
    global w
    w.destroy()
    w = None

class titulo1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font11 = "-family {Segoe UI} -size 10"
        font13 = "-family {Segoe UI} -size 10 -weight bold"
        font14 = "-family {Segoe UI} -size 12 -weight bold"
        font15 = "-family {Segoe UI} -size 11 -weight bold"
        font9 = "-family {Segoe UI} -size 12 -weight bold -underline 1"  \
            ""
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("358x500+810+105")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Alta velocidad")
        top.configure(background="#d9d9d9")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.028, rely=0.02, relheight=0.962, relwidth=0.93)

        self.Canvas1.configure(background="#800000")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(cursor="fleur")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")

        self.lblViajeros = tk.Label(self.Canvas1)
        self.lblViajeros.place(relx=0.06, rely=0.021, height=23, width=112)
        self.lblViajeros.configure(activebackground="#f9f9f9")
        self.lblViajeros.configure(activeforeground="#000000")
        self.lblViajeros.configure(background="#800000")
        self.lblViajeros.configure(disabledforeground="#a3a3a3")
        self.lblViajeros.configure(font=font9)
        self.lblViajeros.configure(foreground="#ffffff")
        self.lblViajeros.configure(highlightbackground="#d9d9d9")
        self.lblViajeros.configure(highlightcolor="black")
        self.lblViajeros.configure(text='''Viajeros:''')

        self.SpinboxViajeros = tk.Spinbox(self.Canvas1, from_=1.0, to=100.0)
        self.SpinboxViajeros.place(relx=0.09, rely=0.083, relheight=0.052
                , relwidth=0.529)
        self.SpinboxViajeros.configure(activebackground="#f9f9f9")
        self.SpinboxViajeros.configure(background="white")
        self.SpinboxViajeros.configure(buttonbackground="#d9d9d9")
        self.SpinboxViajeros.configure(disabledforeground="#a3a3a3")
        self.SpinboxViajeros.configure(font="TkDefaultFont")
        self.SpinboxViajeros.configure(foreground="black")
        self.SpinboxViajeros.configure(highlightbackground="black")
        self.SpinboxViajeros.configure(highlightcolor="black")
        self.SpinboxViajeros.configure(insertbackground="black")
        self.SpinboxViajeros.configure(justify='center')
        self.SpinboxViajeros.configure(selectbackground="#c4c4c4")
        self.SpinboxViajeros.configure(selectforeground="black")
        self.SpinboxViajeros.configure(textvariable=trenIrala_support.cantViajeros)
        self.value_list = ['1','2','3','4','5','6','7','8','9','10',]
        self.SpinboxViajeros.configure(values=self.value_list)

        self.style.map('TCheckbutton',background=
            [('selected', _bgcolor), ('active', _ana2color)])
        self.CheckbuttonIdaVuelta = ttk.Checkbutton(self.Canvas1)
        self.CheckbuttonIdaVuelta.place(relx=0.09, rely=0.166, relwidth=0.535
                , relheight=0.0, height=25)
        self.CheckbuttonIdaVuelta.configure(variable=trenIrala_support.tch49)
        self.CheckbuttonIdaVuelta.configure(takefocus="")
        self.CheckbuttonIdaVuelta.configure(text='''Ida y Vuelta''')

        self.lblClase = tk.Label(self.Canvas1)
        self.lblClase.place(relx=0.03, rely=0.229, height=23, width=82)
        self.lblClase.configure(activebackground="#f9f9f9")
        self.lblClase.configure(activeforeground="#000000")
        self.lblClase.configure(background="#800000")
        self.lblClase.configure(disabledforeground="#a3a3a3")
        self.lblClase.configure(font="-family {Segoe UI} -size 12 -weight bold -underline 1")
        self.lblClase.configure(foreground="#ffffff")
        self.lblClase.configure(highlightbackground="#d9d9d9")
        self.lblClase.configure(highlightcolor="black")
        self.lblClase.configure(text='''Clase:''')

        self.ComboboxClase = ttk.Combobox(self.Canvas1)
        self.ComboboxClase.place(relx=0.09, rely=0.291, relheight=0.054
                , relwidth=0.562)
        self.value_list = ['Turista','Primera','Lujo',]
        self.ComboboxClase.configure(values=self.value_list)
        self.ComboboxClase.configure(font=font11)
        self.ComboboxClase.configure(justify='center')
        self.ComboboxClase.configure(textvariable=trenIrala_support.clase)
        self.ComboboxClase.configure(background="#ffffff")
        self.ComboboxClase.configure(takefocus="")

        self.lblDistancia = tk.Label(self.Canvas1)
        self.lblDistancia.place(relx=0.03, rely=0.353, height=23, width=222)
        self.lblDistancia.configure(activebackground="#f9f9f9")
        self.lblDistancia.configure(activeforeground="#000000")
        self.lblDistancia.configure(background="#800000")
        self.lblDistancia.configure(disabledforeground="#a3a3a3")
        self.lblDistancia.configure(font=font15)
        self.lblDistancia.configure(foreground="#ffffff")
        self.lblDistancia.configure(highlightbackground="#d9d9d9")
        self.lblDistancia.configure(highlightcolor="black")
        self.lblDistancia.configure(text='''Distancia (Kilometros):''')

        self.EntDistancia = tk.Entry(self.Canvas1)
        self.EntDistancia.place(relx=0.09, rely=0.437, height=26, relwidth=0.562)

        self.EntDistancia.configure(background="white")
        self.EntDistancia.configure(disabledforeground="#a3a3a3")
        self.EntDistancia.configure(font="TkFixedFont")
        self.EntDistancia.configure(foreground="#000000")
        self.EntDistancia.configure(insertbackground="black")
        self.EntDistancia.configure(justify='center')
        self.EntDistancia.configure(textvariable=trenIrala_support.distancia)

        self.lblPrecio = tk.Label(self.Canvas1)
        self.lblPrecio.place(relx=0.03, rely=0.499, height=23, width=82)
        self.lblPrecio.configure(activebackground="#f9f9f9")
        self.lblPrecio.configure(activeforeground="#000000")
        self.lblPrecio.configure(background="#800000")
        self.lblPrecio.configure(disabledforeground="#a3a3a3")
        self.lblPrecio.configure(font="-family {Segoe UI} -size 12 -weight bold -underline 1")
        self.lblPrecio.configure(foreground="#ffffff")
        self.lblPrecio.configure(highlightbackground="#d9d9d9")
        self.lblPrecio.configure(highlightcolor="black")
        self.lblPrecio.configure(text='''Precio:''')

        self.EntPrecio = tk.Entry(self.Canvas1)
        self.EntPrecio.place(relx=0.09, rely=0.561,height=26, relwidth=0.562)
        self.EntPrecio.configure(background="white")
        self.EntPrecio.configure(disabledforeground="#a3a3a3")
        self.EntPrecio.configure(font="TkFixedFont")
        self.EntPrecio.configure(foreground="#000000")
        self.EntPrecio.configure(highlightbackground="#d9d9d9")
        self.EntPrecio.configure(highlightcolor="black")
        self.EntPrecio.configure(insertbackground="black")
        self.EntPrecio.configure(justify='center')
        self.EntPrecio.configure(selectbackground="#c4c4c4")
        self.EntPrecio.configure(selectforeground="black")
        self.EntPrecio.configure(textvariable=trenIrala_support.precio)

        self.lblPagar = tk.Label(self.Canvas1)
        self.lblPagar.place(relx=0.06, rely=0.624, height=33, width=162)
        self.lblPagar.configure(activebackground="#f9f9f9")
        self.lblPagar.configure(activeforeground="#000000")
        self.lblPagar.configure(background="#800000")
        self.lblPagar.configure(cursor="fleur")
        self.lblPagar.configure(disabledforeground="#a3a3a3")
        self.lblPagar.configure(font=font14)
        self.lblPagar.configure(foreground="#ffffff")
        self.lblPagar.configure(highlightbackground="#d9d9d9")
        self.lblPagar.configure(highlightcolor="black")
        self.lblPagar.configure(text='''A pagar (Euros):''')

        self.lblTotalPagar = tk.Label(self.Canvas1)
        self.lblTotalPagar.place(relx=0.06, rely=0.707, height=26, width=182)
        self.lblTotalPagar.configure(anchor='e')
        self.lblTotalPagar.configure(background="#000000")
        self.lblTotalPagar.configure(disabledforeground="#a3a3a3")
        self.lblTotalPagar.configure(font=font13)
        self.lblTotalPagar.configure(foreground="#ffff00")
        self.lblTotalPagar.configure(justify='right')
        self.lblTotalPagar.configure(text="")

        self.btnCalcular = tk.Button(self.Canvas1)
        self.btnCalcular.place(relx=0.06, rely=0.811, height=33, width=136)
        self.btnCalcular.configure(activebackground="#ececec")
        self.btnCalcular.configure(activeforeground="#000000")
        self.btnCalcular.configure(background="#d9d9d9")
        self.btnCalcular.configure(command=trenIrala_support.calcular)
        self.btnCalcular.configure(disabledforeground="#a3a3a3")
        self.btnCalcular.configure(font=font13)
        self.btnCalcular.configure(foreground="#000000")
        self.btnCalcular.configure(highlightbackground="#d9d9d9")
        self.btnCalcular.configure(highlightcolor="black")
        self.btnCalcular.configure(pady="0")
        self.btnCalcular.configure(text='''Calcular''')

        self.btnSalir = tk.Button(self.Canvas1)
        self.btnSalir.place(relx=0.511, rely=0.811, height=33, width=136)
        self.btnSalir.configure(activebackground="#ececec")
        self.btnSalir.configure(activeforeground="#000000")
        self.btnSalir.configure(background="#d9d9d9")
        self.btnSalir.configure(command=trenIrala_support.salir)
        self.btnSalir.configure(disabledforeground="#a3a3a3")
        self.btnSalir.configure(font=font13)
        self.btnSalir.configure(foreground="#000000")
        self.btnSalir.configure(highlightbackground="#d9d9d9")
        self.btnSalir.configure(highlightcolor="black")
        self.btnSalir.configure(pady="0")
        self.btnSalir.configure(text='''Salir''')

if __name__ == '__main__':
    vp_start_gui()





