#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 14, 2020 10:12:25 AM -03  platform: Windows NT
########################## Proyecto Sistema Pasajes de Tren#########################################################
########################## Ramirez Damian Andres ###################################################################
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global spinbox
    spinbox = tk.IntVar()
    global EntryDis
    EntryDis = tk.StringVar()
    global EntryPre
    EntryPre = tk.StringVar()
    global Entrycos
    Entrycos = tk.StringVar()
    global R2_tur
    R2_tur = tk.IntVar()
    global R3_prim
    R3_prim = tk.IntVar()
    global R3_vip
    R3_vip = tk.IntVar()
    global R1_ida
    R1_ida = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def calculo():
    sel01 = R1_ida.get()
    sel02 = R2_tur.get()
    sel03 = R3_prim.get()
    sel04 = R3_vip.get()
    viajeros = int(spinbox.get())
    distancia = float(EntryDis.get())
    distancia *=0.10
    precio = int(EntryPre.get())
    total = viajeros*distancia*precio

    if sel01 == 0 and sel02 == 0 and sel04 == 0:
        lbl_total = tk.Label(text="Su Importe es: " + f"{total}",
                             activebackground="#000000",
                             activeforeground="white",
                             background="#000000",
                             disabledforeground="#000000",
                             font='font11',
                             foreground="#ffff00",
                             highlightbackground="#000000",
                             highlightcolor="#000000")
        lbl_total.place(relx=0.25, rely=0.849, height=20, width=150)
    if sel01 == 1:
        total *=1.5
        if sel03 == 1:
            total *= 1.2
        if sel04 == 1:
            total *= 2
        lbl_total = tk.Label(text="Su Importe es: " + f"{total}",
                             activebackground="#000000",
                             activeforeground="white",
                             background="#000000",
                             disabledforeground="#000000",
                             font ='font11',
                             foreground="#ffff00",
                             highlightbackground="#000000",
                             highlightcolor="#000000")
        lbl_total.place(relx=0.25, rely=0.849, height=20, width=150)

def destroy_Toplevel1(p1):
    print('Viajero01_support.destroy_Toplevel1')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Viajero01
    Viajero01.vp_start_gui()

